<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <UserSecretsId>ca29df9c-1331-4e36-965e-d9e14793e929</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SwipePages.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Behaviors\right.png" />
    <None Remove="fire.png" />
    <None Remove="fire2.png" />
    <None Remove="fonts\Hindmedium.ttf" />
    <None Remove="fonts\NotoSansTaiViet-Regular.ttf" />
    <None Remove="Group 7.png" />
    <None Remove="Inter-Regular.ttf" />
    <None Remove="minifire.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="fire.png" />
    <EmbeddedResource Include="fire2.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="fonts\Hindmedium.ttf" />
    <EmbeddedResource Include="fonts\NotoSansTaiViet-Regular.ttf" />
    <EmbeddedResource Include="fonts\Inter-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="Plugin.FirebasePushNotification" Version="3.4.35" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="2.0.6" />
    <PackageReference Include="Xamarin.Essentials" Version="1.8.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2662" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="PhoneLog.xaml.cs">
      <DependentUpon>PhoneLog.xaml</DependentUpon>
    </Compile>
    <Compile Update="information.xaml.cs">
      <DependentUpon>information.xaml</DependentUpon>
    </Compile>
    <Compile Update="account_deleting.xaml.cs">
      <DependentUpon>account_deleting.xaml</DependentUpon>
    </Compile>
    <Compile Update="settings.xaml.cs">
      <DependentUpon>settings.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="AddReactionPopup.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="confirm.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="homepage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="popup1.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="popup2.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="reactionslist.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="register.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="streakpopuppage.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="welcome.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="widgettutorial.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
	<ItemGroup>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="App.xaml.cs">
			<DependentUpon>*.xaml</DependentUpon>
		</Compile>
		<Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="MainPage.xaml.cs">
			<DependentUpon>*.xaml</DependentUpon>
		</Compile>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="images\" />
    <Folder Include="Models\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Behaviors\right.png" />
    <Reference Include="Mono.Android">
      <HintPath>..\..\..\..\..\VisualStudio2022\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v11.0\Mono.Android.dll</HintPath>
    </Reference>
    <Resource Include="SwipePages.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="menubutton.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>